config/routes.rb
Rails.application.routes.draw do

	root 'employees#index'

	get 'query' => 'query#index'

  get 'settings' => 'settings#index'
  patch 'settings' => 'settings#update'

	delete 'clear_employees' => 'employees_manage#clear'

	get 'employees_manage' => 'employees_manage#index'
	post 'employees_manage' => 'employees_manage#create'
  get 'employees_export' => 'employees_manage#export'

  get 'records' => 'annual_leave_change_records#index'

  get 'records_manage' => 'annual_leave_change_records_manage#index'
  post 'records_manage' => 'annual_leave_change_records_manage#import'
  get 'records_export' => 'annual_leave_change_records_manage#export'

	get 'login' => 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'

  resources :employees

	resources :annual_leave_change_records

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :annual_leave_change_records, dependent: :destroy
	default_scope -> { order(staffno: :ASC) }

	validates :name, presence: true
	validates :staffno, uniqueness: true,
											length: { is: 8 }
	validates :hiredate, presence: true
	validates :seniority, numericality: {
													only_integer: true,
													greater_than_or_equal_to: 0,
													less_than_or_equal_to: 35
												}

	validates :last_year_left, presence: true,
															numericality: true

	#当前工龄
	attr_accessor :seniority, #工龄
	              :statutory, #法定年假
	              :extra, #额外年假
	              :bonus, #公司福利年假
	              :used, #已休年假
	              :remain #剩余年假

	COLUMN_NAME = 'name'                        #姓名
	COLUMN_STAFFNO = 'staffno'                  #员工号
	COLUMN_SENIORITY = 'seniority'              #工龄
	COLUMN_HIREDATE = "hiredate"                #入职日期
	COLUMN_LAST_YEAR_LEFT = "last_year_left"    #去年剩余年假

	before_save {
		self.start_work_year = Time.now.year.to_i - self.seniority.to_i
	}

	after_find do |employee|
		employee.seniority = Time.now.year.to_i - self.start_work_year.to_i;
		includeLastYear = Setting.first.includeLastYear
		if includeLastYear
			initAnnualLeaveInfoIncludeLastYear(employee)
		else
			initAnnualLeaveInfoWithoutLastYear(employee)
		end
	end

	def initAnnualLeaveInfoIncludeLastYear(employee)
		employee.last_year_left ||= 0.0
		employee.statutory = 0.0
		employee.bonus = 0.0

		this_year_i = Time.now.year.to_i
		last_year_i = this_year_i - 1
		employee.extra = employee.annual_leave_change_records.where(
			kind: AnnualLeaveChangeRecord::KIND_EXTRA, which_year: (last_year_i..this_year_i)).sum(:number)
		employee.used = employee.annual_leave_change_records.where(
			kind: AnnualLeaveChangeRecord::KIND_USED, which_year: (last_year_i..this_year_i)).sum(:number)
		employee.statutory = getStatutory
		employee.bonus = getBonus(employee)
		employee.remain = employee.last_year_left + employee.statutory + employee.extra + employee.bonus - employee.used
	end


	def initAnnualLeaveInfoWithoutLastYear(employee)
		employee.last_year_left = 0.0
		employee.statutory = 0.0
		employee.bonus = 0.0

		this_year_i = Time.now.year.to_i
		last_year_i = this_year_i - 1
		employee.extra = employee.annual_leave_change_records.where(
			kind: AnnualLeaveChangeRecord::KIND_EXTRA, which_year: this_year_i).sum(:number)
		employee.used = employee.annual_leave_change_records.where(
			kind: AnnualLeaveChangeRecord::KIND_USED,  which_year: this_year_i).sum(:number)
		employee.statutory = getStatutory
		employee.bonus = getBonus(employee)
		employee.remain = employee.last_year_left + employee.statutory + employee.extra + employee.bonus - employee.used
	end

	def getStatutoryBase
		seniority = self.seniority.to_i
		if seniority >= 1 && seniority < 10 #累计工作满一年不满10年的
			statutory_base = 5
		elsif seniority >= 10 && seniority < 20 #已满10年不满20年
			statutory_base = 10
		elsif seniority >= 20 #年满20年的
			statutory_base = 15
		else
			statutory_base = 0
		end
		statutory_base
	end

	DAY_ANNUAL_LEAVE_CALCULATE_FROM = Time.new(Time.now.year, 1, 1)
	# 根据开始工作时间和入职日期计算法定年假
	# （导入的原始数据是当前工龄，需要换算成开始工作时间再进行计算，存入的也是开始工作时间）
	def getStatutory
		statutory_base = getStatutoryBase

		elapseddays = elapsed_days(self.hiredate > DAY_ANNUAL_LEAVE_CALCULATE_FROM ?
			                           self.hiredate : DAY_ANNUAL_LEAVE_CALCULATE_FROM,
															Time.now)

		#年假最小单位为0.5天
		(elapseddays * statutory_base / 365.0 * 2).to_i / 2.0
	end

	#入职日期是否在三个月之内
	def in_three_months
		self.hiredate > DateTime.now.prev_month(3)
	end

	#返回相差的天数
	def elapsed_days(from, to)
		((to - from) / 24.hours ).to_i
	end

	#公司福利年假
	def getBonus(employee)
		now = Time.now
		bonus = 0.5 * (now.year - employee.hiredate.year - 1)
		bonus < 0 ? 0 : bonus
	end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_action :logged_in_user
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
		@includeLastYear = Setting.first.includeLastYear
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)
		if @employee.save
			#TODO
			redirect_to employees_url
		else
			#TODO
			render :new
		end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html {
	        flash[:success] = "#{@employee.name} 信息更新成功"
	        redirect_to root_path
        }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :staffno, :seniority, :hiredate, :last_year_left)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "姓名" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label '工号' %><br>
    <%= f.text_field :staffno %>
  </div>
  <div class="field">
    <%= f.label '工龄' %><br>
    <%= f.number_field :seniority %>
  </div>
  <div class="field">
    <%= f.label '入职日期' %><br>
      <% if @employee.hiredate.nil? %>
          <%= f.text_field :hiredate %>
      <% else %>
          <%= f.text_field :hiredate, value: @employee.hiredate.strftime("%Y-%m-%d") %>
      <% end %>
  </div>
    <div class="field">
        <%= f.label '去年剩余' %><br>
        <%= f.text_field :last_year_left %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-1"><%= link_to ' 添加新员工', new_employee_path  %>
    <div class="panel panel-default templatemo-content-widget white-bg no-padding templatemo-overflow-hidden">
        <i class="fa fa-times"></i>

        <div class="panel-heading templatemo-position-relative">
            <h2 class="text-uppercase">Listing Employees</h2>
        </div>

        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>姓名</th>
                    <th>员工号</th>
                    <th>工龄</th>
                    <th>入职日期</th>
                    <% if @includeLastYear %>
                        <th>去年剩余</th>
                    <% end %>
                    <th>法定</th>
                    <th>奖励</th>
                    <th>福利</th>
                    <th>已休</th>
                    <th>剩余</th>
                </tr>
                </thead>

                <tbody>
                <% @employees.each do |employee| %>
                    <tr>
                        <td>
                            <%= link_to  employee.name, edit_employee_path(employee)  %>
                        </td>
                        <td><%= employee.staffno %></td>
                        <td><%= employee.seniority %></td>
                        <td><%= employee.hiredate.strftime("%Y-%m-%d") %></td>
                        <% if @includeLastYear %>
                            <td><%= employee.last_year_left %></td>
                        <% end %>
                        <td><%= employee.statutory %></td>
                        <td><%= employee.extra %>
                            <%= link_to ' +', new_annual_leave_change_record_path(
                                                    kind: AnnualLeaveChangeRecord::KIND_EXTRA,
                                                    employee_id: employee.id)  %></td>
                        <td><%= employee.bonus %></td>
                        <td><%= employee.used %>
                            <%= link_to ' +', new_annual_leave_change_record_path(
                                                    kind: AnnualLeaveChangeRecord::KIND_USED,
                                                    employee_id: employee.id)  %></td>
                        <td><%= employee.remain %></td>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Staffno:</strong>
  <%= @employee.staffno %>
</p>

<p>
  <strong>Start work date:</strong>
  <%= @employee.start_work_date %>
</p>

<p>
  <strong>Hiredate:</strong>
  <%= @employee.hiredate %>
</p>

<p>
  <strong>Statutory:</strong>
  <%= @employee.statutory %>
</p>

<p>
  <strong>Extra:</strong>
  <%= @employee.extra %>
</p>

<p>
  <strong>Bonus:</strong>
  <%= @employee.bonus %>
</p>

<p>
  <strong>Used:</strong>
  <%= @employee.used %>
</p>

<p>
  <strong>Remain:</strong>
  <%= @employee.remain %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>