config/routes.rb
Rails.application.routes.draw do

	root 'employees#index'

	get 'query' => 'query#index'

  get 'settings' => 'settings#index'
  patch 'settings' => 'settings#update'

	delete 'clear_employees' => 'employees_manage#clear'

	get 'employees_manage' => 'employees_manage#index'
	post 'employees_manage' => 'employees_manage#create'
  get 'employees_export' => 'employees_manage#export'

  get 'records' => 'annual_leave_change_records#index'

  get 'records_manage' => 'annual_leave_change_records_manage#index'
  post 'records_manage' => 'annual_leave_change_records_manage#import'
  get 'records_export' => 'annual_leave_change_records_manage#export'

	get 'login' => 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'

  resources :employees

	resources :annual_leave_change_records

end

app/controllers/employees_manage_controller.rb
class EmployeesManageController < ApplicationController
	before_action :logged_in_user

	def index
		@employee_import = EmployeeImport.new
	end

	def create
		@employee_import = EmployeeImport.new(params[:employee_import])
		if @employee_import.save
			redirect_to root_url, notice: "Imported employees successfully."
		else
			render :index
		end
	end

	def clear
		if Employee.destroy_all
			redirect_to root_url
		else
			render :index
		end
	end

	def export
		@employees = Employee.all
		respond_to do |format|
			format.xls
		end
	end
end

app/helpers/employees_manage_helper.rb
module EmployeesManageHelper
end

app/views/employees_manage/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
    <Worksheet ss:Name="员工年假信息">
        <Table>
            <Row>
                <Cell><Data ss:Type="String">姓名</Data></Cell>
                <Cell><Data ss:Type="String">员工号</Data></Cell>
                <Cell><Data ss:Type="String">工龄</Data></Cell>
                <Cell><Data ss:Type="String">入职日期</Data></Cell>
                <Cell><Data ss:Type="String">法定</Data></Cell>
                <Cell><Data ss:Type="String">奖励</Data></Cell>
                <Cell><Data ss:Type="String">福利</Data></Cell>
                <Cell><Data ss:Type="String">已休</Data></Cell>
                <Cell><Data ss:Type="String">剩余</Data></Cell>
            </Row>
            <% @employees.each do |employee| %>
                <Row>
                    <Cell><Data ss:Type="String"><%= employee.name %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= employee.staffno %></Data></Cell>
                    <Cell><Data ss:Type="Number"><%= employee.seniority %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= employee.hiredate.strftime("%Y-%m-%d") %></Data></Cell>
                    <Cell><Data ss:Type="Number"><%= employee.statutory %></Data></Cell>
                    <Cell><Data ss:Type="Number"><%= employee.extra %></Data></Cell>
                    <Cell><Data ss:Type="Number"><%= employee.bonus %></Data></Cell>
                    <Cell><Data ss:Type="Number"><%= employee.used %></Data></Cell>
                    <Cell><Data ss:Type="Number"><%= employee.remain %></Data></Cell>
                </Row>
            <% end %>
        </Table>
    </Worksheet>
</Workbook>

app/views/employees_manage/index.html.erb
<h1>员工信息管理</h1>

<p>导入文件格式为excel表格，表格第一行为表头，表格格式如下(括号及括号中内容为说明)：</p>

<table class="table table-bordered">
    <thead>
    <tr>
        <th><%= Employee::COLUMN_NAME %>(姓名)</th>
        <th><%= Employee::COLUMN_STAFFNO %>(员工号)</th>
        <th><%= Employee::COLUMN_SENIORITY %>(工龄)</th>
        <th><%= Employee::COLUMN_HIREDATE %>(入职日期)</th>
        <th><%= Employee::COLUMN_LAST_YEAR_LEFT %>(去年剩余年假)</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>路人甲</td>
        <td>10010123</td>
        <td>8</td>
        <td>20130101</td>
        <td>2.5</td>
    </tr>
    </tbody>
</table>

<p>

<%= form_for @employee_import, url: employees_manage_path do |f| %>
    <% if @employee_import.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@employee_import.errors.count, "error") %> prohibited this import from completing:</h2>
            <ul>
                <% @employee_import.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.file_field :file %>
    <%= f.submit "导入" %>
<% end %>

</p>

<%= link_to '导出所有员工年假信息', employees_export_path(format: 'xls'), method: :get %><br><br><br>

<%= link_to '删除所有员工和休假记录', clear_employees_path, method: :delete, data: { confirm: '你要再好好想想吗?' } %>