config/routes.rb
Rails.application.routes.draw do

	root 'employees#index'

	get 'query' => 'query#index'

  get 'settings' => 'settings#index'
  patch 'settings' => 'settings#update'

	delete 'clear_employees' => 'employees_manage#clear'

	get 'employees_manage' => 'employees_manage#index'
	post 'employees_manage' => 'employees_manage#create'
  get 'employees_export' => 'employees_manage#export'

  get 'records' => 'annual_leave_change_records#index'

  get 'records_manage' => 'annual_leave_change_records_manage#index'
  post 'records_manage' => 'annual_leave_change_records_manage#import'
  get 'records_export' => 'annual_leave_change_records_manage#export'

	get 'login' => 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'

  resources :employees

	resources :annual_leave_change_records

end

app/controllers/annual_leave_change_records_manage_controller.rb
class AnnualLeaveChangeRecordsManageController < ApplicationController
	before_action :logged_in_user
	
	def index
		@record_import = AnnualLeaveChangeRecordImport.new
	end

	def import
		@record_import = AnnualLeaveChangeRecordImport.new(params[:annual_leave_change_record_import])
		if @record_import.save
			redirect_to root_url, notice: "Imported records successfully."
		else
			render :index
		end
	end

	def export
		from_date = Date.parse(params[:export_params][:from_date])
		to_date = Date.parse(params[:export_params][:to_date]) + 1
		@records = AnnualLeaveChangeRecord.all.where(kind: AnnualLeaveChangeRecord::KIND_USED, when: from_date..to_date)
		respond_to do |format|
			format.xls
		end
	end
end

app/helpers/annual_leave_change_records_manage_helper.rb
module AnnualLeaveChangeRecordsManageHelper
end

app/views/annual_leave_change_records_manage/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
    <Worksheet ss:Name="休假记录">
        <Table>
            <Row>
                <Cell><Data ss:Type="String">姓名</Data></Cell>
                <Cell><Data ss:Type="String">员工号</Data></Cell>
                <Cell><Data ss:Type="String">日期</Data></Cell>
                <Cell><Data ss:Type="String">天数</Data></Cell>
                <Cell><Data ss:Type="String">使用哪年年假</Data></Cell>
            </Row>
            <% @records.each do |record| %>
                <% employee = record.employee %>
                <Row>
                    <Cell><Data ss:Type="String"><%= employee.name %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= employee.staffno %></Data></Cell>
                    <Cell><Data ss:Type="String"><%= record.when.strftime("%Y-%m-%d") %></Data></Cell>
                    <Cell><Data ss:Type="Number"><%= record.number %></Data></Cell>
                    <Cell><Data ss:Type="Number"><%= record.which_year %></Data></Cell>
                </Row>
            <% end %>
        </Table>
    </Worksheet>
</Workbook>

app/views/annual_leave_change_records_manage/index.html.erb
<h1>年假变动记录导入</h1>

<p>导入文件格式为excel表格，表格第一行为表头，表格格式如下(括号及括号中内容为说明)：</p>

<table class="table table-bordered">
    <thead>
    <tr>
        <th><%= AnnualLeaveChangeRecord::COLUMN_STAFFNO %>(员工号)</th>
        <th><%= AnnualLeaveChangeRecord::COLUMN_KIND %>(变更类型：1-休假，2-新增)</th>
        <th><%= AnnualLeaveChangeRecord::COLUMN_WHEN %>(变更日期)</th>
        <th><%= AnnualLeaveChangeRecord::COLUMN_NUMBER %>(天数)</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>10010123</td>
        <td>1</td>
        <td>20130101</td>
        <td>2.5</td>
    </tr>
    </tbody>
</table>


<%= form_for @record_import, url: records_manage_path do |f| %>
    <% if @record_import.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@record_import.errors.count, "error") %> prohibited this import from completing:</h2>
            <ul>
                <% @record_import.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.file_field :file %>
    </div>
    <div class="buttons"><%= f.submit "导入" %></div>
<% end %>

<%= form_for :export_params, url: records_export_path(format: "xls"), method: 'get' do |f| %>
<% last_month_first_day = DateTime.now.prev_month.at_beginning_of_month %>
<% last_month_last_day = DateTime.now.prev_month.at_end_of_month %>
<%= f.date_field :from_date, value: last_month_first_day.strftime("%Y-%m-%d") %>
<%= f.date_field :to_date, max: Date.today, value: last_month_last_day.strftime("%Y-%m-%d") %>
<%= f.submit "导出休假记录" %>
<% end %>